---
- hosts: [all]
  tasks:
  - name: Remove file
    file:
      path: /home/user_test/hello.txt
      state: absent

  - name: Remove user
    user:
      name: user_test
      state: absent

  - name: Remove nginx*
    apt:
      name: nginx
      state: absent